[package]
name = "librashader-reflect"
edition = "2021"

license = "MPL-2.0 OR GPL-3.0-only"
version = "0.1.0-beta.12"
authors = ["Ronny Chan <ronny@ronnychan.ca>"]
repository = "https://github.com/SnowflakePowered/librashader"
readme = "../README.md"
categories = ["emulators", "compilers", "graphics"]
keywords = ["shader", "retroarch", "SPIR-V"]
description = "RetroArch shaders for all."

[dependencies]
shaderc = { version = "0.8.2", features = [] }
spirv_cross = { package = "librashader-spirv-cross", version = "0.23", features = [ "glsl", "hlsl" ] }

thiserror = "1.0.37"
bitflags = "1.3.2"
rustc-hash = "1.1.0"

librashader-common = { path = "../librashader-common", version = "0.1.0-beta.12" }
librashader-preprocess = { path = "../librashader-preprocess", version = "0.1.0-beta.12" }
librashader-presets = { path = "../librashader-presets", version = "0.1.0-beta.12" }

spirv-to-dxil = { version = "0.2", optional = true }
naga = { version = "0.10.0", features = ["glsl-in", "spv-in", "spv-out", "glsl-out", "wgsl-out"], optional = true }

bytemuck = "1.13.0"
rspirv = { version = "0.11.0+1.5.4", optional = true }

[features]
default = ["dxil"]
unstable-naga = [ "naga", "rspirv" ]
standalone = ["shaderc/build-from-source"]
dxil = ["spirv-to-dxil"]

[dev-dependencies]

[package.metadata.docs.rs]
features = ["spirv-to-dxil/included-bindings"]
