[package]
name = "librashader-reflect"
edition = "2021"

license = "MPL-2.0 OR GPL-3.0-only"
version = "0.1.0-beta.3"
authors = ["Ronny Chan <ronny@ronnychan.ca>"]
repository = "https://github.com/SnowflakePowered/librashader"
readme = "../README.md"
categories = ["emulators", "compilers", "graphics"]
keywords = ["shader", "retroarch", "SPIR-V"]
description = "RetroArch shaders for all."

[dependencies]
shaderc = { version = "0.8.1", features = [] }
spirv_cross = { version = "0.23.1", features = [ "glsl", "hlsl" ] }


thiserror = "1.0.37"
bitflags = "1.3.2"
rustc-hash = "1.1.0"

librashader-common = { path = "../librashader-common", version = "0.1.0-beta.3" }
librashader-preprocess = { path = "../librashader-preprocess", version = "0.1.0-beta.3" }

naga = { version = "0.10.0", features = ["glsl-in", "spv-in", "spv-out", "glsl-out", "wgsl-out"], optional = true }
rspirv = { version = "0.11.0+1.5.4", optional = true }
rspirv-reflect = { git = "https://github.com/Traverse-Research/rspirv-reflect", optional = true, version = "0.7.0" }

[features]
default = []
unstable-rust-pipeline = [ "naga", "rspirv", "rspirv-reflect" ]
standalone = ["shaderc/build-from-source"]

[dev-dependencies]
