[workspace]
members = [
    "librashader",
    "librashader-common",
    "librashader-presets",
    "librashader-preprocess",
    "librashader-reflect",
    "librashader-runtime-d3d11",
    "librashader-runtime-gl",
    "librashader-runtime-gl46",
]