[workspace]
members = [
    "librashader",
    "librashader-presets",
    "librashader-preprocess",
    "librashader-reflect",
    "librashader-runtime-dx11",
    "librashader-runtime-gl",
    "naga"
]