language = "C"
cpp_compat = true
include_guard = "__LIBRASHADER_H__"
pragma_once = true
usize_is_size_t = true
documentation_style = "c++"
after_includes = "#ifdef _WIN32 && RUNTIME_D3D11 \n#include <d3d11.h>\n#else\ntypedef void ID3D11Device;typedef void ID3D11RenderTargetView;typedef void ID3D1ShaderResourceView;\n#endif"



[defines]
"feature = runtime-opengl" = "LIBRA_RUNTIME_OPENGL"
"feature = runtime-d3d11" = "LIBRA_RUNTIME_D3D11"

[parse]
parse_deps = true
include = ["librashader",
    "librashader-presets",
    "librashader-preprocess",
    "librashader-reflect",
    "librashader-runtime-gl",
    "librashader-runtime-d3d11"
]
expand = ["librashader-capi"]

[struct]

[enum]
rename_variants = "ScreamingSnakeCase"
prefix_with_name = true

[export]
include = [
    # preset
    "PFN_libra_load_preset",
    "PFN_libra_preset_free",
    "PFN_libra_preset_set_param",
    "PFN_libra_preset_get_param",
    "PFN_libra_preset_print",
    "PFN_libra_preset_get_runtime_param_names",

    # error
    "PFN_libra_error_errno",
    "PFN_libra_error_print",
    "PFN_libra_error_free",
    "PFN_libra_error_write",
    "PFN_libra_error_free_string",

    # gl
    "PFN_libra_gl_init_context",
    "PFN_libra_gl_filter_chain_create",
    "PFN_libra_gl_filter_chain_frame",
    "PFN_libra_gl_filter_chain_free",

    # d3d11
    "PFN_libra_d3d11_filter_chain_create",
    "PFN_libra_d3d11_filter_chain_frame",
    "PFN_libra_d3d11_filter_chain_free",
]

[export.rename]
"LibrashaderError" = "_libra_error"
"ShaderPreset" = "_shader_preset"
"FilterChainGL" = "_filter_chain_gl"
"FilterChainOptionsGL" = "filter_chain_gl_opt_t"
"FrameOptionsGL" = "frame_gl_opt_t"
"FilterChainD3D11" = "_filter_chain_d3d11"
"FilterChainOptionsD3D11" = "filter_chain_d3d11_opt_t"
"FrameOptionsD3D11" = "frame_d3d11_opt_t"