[package]
name = "librashader"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

license = "MPL-2.0 OR GPL-3.0-only"
version = "0.1.0-alpha.4"
authors = ["Ronny Chan <ronny@ronnychan.ca>"]
repository = "https://github.com/SnowflakePowered/librashader"
readme = "../README.md"
categories = ["emulators", "compilers", "graphics"]
keywords = ["shader", "retroarch", "SPIR-V"]
description = "RetroArch shaders for all."

[dependencies]
librashader-common = { path = "../librashader-common", version = "0.1.0-alpha.4" }
librashader-presets = { path = "../librashader-presets", version = "0.1.0-alpha.4" }
librashader-preprocess = { path = "../librashader-preprocess", version = "0.1.0-alpha.4" }
librashader-reflect = { path = "../librashader-reflect", version = "0.1.0-alpha.4", features = ["standalone"] }
librashader-runtime  = { path = "../librashader-runtime", version = "0.1.0-alpha.4" }
librashader-runtime-d3d11  = { path = "../librashader-runtime-d3d11", version = "0.1.0-alpha.4" }
librashader-runtime-gl = { path = "../librashader-runtime-gl", version = "0.1.0-alpha.4" }
librashader-runtime-vk = { path = "../librashader-runtime-vk", version = "0.1.0-alpha.4" }


[features]
default = ["gl", "d3d11", "vk", "reflect", "preprocess", "presets" ]
gl = [ "runtime", "librashader-common/opengl" ]
d3d11 = [ "runtime", "librashader-common/d3d11" ]
vk = ["runtime", "librashader-common/vulkan" ]
runtime = []
reflect = []
preprocess = []
presets = []
