[package]
name = "librashader"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

license = "MPL-2.0 OR GPL-3.0-only"
version = "0.1.0-beta.3"
authors = ["Ronny Chan <ronny@ronnychan.ca>"]
repository = "https://github.com/SnowflakePowered/librashader"
readme = "../README.md"
categories = ["emulators", "compilers", "graphics"]
keywords = ["shader", "retroarch", "SPIR-V"]
description = "RetroArch shaders for all."

[dependencies]
librashader-common = { path = "../librashader-common", version = "0.1.0-beta.3" }
librashader-presets = { path = "../librashader-presets", version = "0.1.0-beta.3" }
librashader-preprocess = { path = "../librashader-preprocess", version = "0.1.0-beta.3" }
librashader-reflect = { path = "../librashader-reflect", version = "0.1.0-beta.3", features = ["standalone"] }
librashader-runtime  = { path = "../librashader-runtime", version = "0.1.0-beta.3" }
librashader-runtime-d3d11  = { path = "../librashader-runtime-d3d11", version = "0.1.0-beta.3", optional = true }
librashader-runtime-gl = { path = "../librashader-runtime-gl", version = "0.1.0-beta.3", optional = true }
librashader-runtime-vk = { path = "../librashader-runtime-vk", version = "0.1.0-beta.3", optional = true }

ash = { version = "0.37.1+1.3.235", optional = true }

[target.'cfg(windows)'.dependencies.windows]
version = "0.43.0"
features = [
    "Win32_Graphics_Direct3D11",
]
optional = true

[features]
default = ["gl", "d3d11", "vk", "reflect", "preprocess", "presets" ]
gl = [ "runtime", "librashader-common/opengl", "librashader-runtime-gl" ]
d3d11 = [ "runtime", "librashader-common/d3d11", "librashader-runtime-d3d11", "windows" ]
vk = ["runtime", "librashader-common/vulkan", "librashader-runtime-vk", "ash" ]
runtime = []
reflect = []
preprocess = []
presets = []

[package.metadata.docs.rs]
targets = ["x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu"]
