[package]
name = "librashader"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

license = "MPL-2.0 OR GPL-3.0-only"
version = "0.1.0-alpha.1"
authors = ["Ronny Chan <ronny@ronnychan.ca>"]
repository = "https://github.com/SnowflakePowered/librashader"
readme = "../README.md"
categories = ["emulators", "compilers", "graphics"]
keywords = ["shader", "retroarch", "SPIR-V"]
description = "RetroArch shaders for all."

[dependencies]
librashader-common = { path = "../librashader-common", version = "0.1.0-alpha.1"  }
librashader-presets = { path = "../librashader-presets", version = "0.1.0-alpha.1"  }
librashader-preprocess = { path = "../librashader-preprocess", version = "0.1.0-alpha.1"  }
librashader-reflect = { path = "../librashader-reflect", version = "0.1.0-alpha.1"  }
librashader-runtime  = { path = "../librashader-runtime", version = "0.1.0-alpha.1"  }
librashader-runtime-d3d11  = { path = "../librashader-runtime-d3d11", version = "0.1.0-alpha.1"  }
librashader-runtime-gl = { path = "../librashader-runtime-gl", version = "0.1.0-alpha.1"  }


[features]
gl = [ "librashader-common/opengl" ]
d3d11 = [ "librashader-common/d3d11" ]
