[package]
name = "librashader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "opengl" ]
opengl = ["gl"]

[dependencies]
gl = { version = "0.14.0", optional = true }