name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup cargo post
      uses: baptiste0928/cargo-install@bf6758885262d0e6f61089a9d8c8790d3ac3368f
      with:
        crate: cargo-post
    - name: Build dynamic library
      run: cargo post build --release --package librashader-capi
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: build-outputs
        path: "target"
